### PR TITLE
Completed Filipino Translation - 1682 total translated words

### PR DESCRIPTION
**Pull request by mind-blast**
Filipino Translation - 1264 total translated words.
Leaving untranslated git codes and system generated words on enclosed git code commands.

### CODE REVIEW

**Comment by mind-blast** [comment]
Completed 100% translation for this file . total 1682 translated words. Edit some translated words.

**Comment by cricketsport** [comment]
how to translate i want to try it? is it okay for all languages?

**Comment by severinolorillajr** [comment]
Thanks for the contribution @robin-ho , I will review your submission in a while.
@cricketsport , no this is only for tagalog translations, you can check the official progit repository for further guidelines and information.

**Comment by severinolorillajr** [comment]
@robin-ho , I have done reviewing your translations. Please update them accordingly, based on what I have suggested. Once you are done, please leave a message here so I can do one last check.

By the way, I have only reviewed remotes.asc.
Your new commit is still not included.

**Comment by mind-blast** [comment]
@severinolorillajr  I have checked again my translation and done some proof reading for remotes.asc
As for tagging.asc it is still a partial translation. I am still working on my next set on it.
Thank you.

**Comment by severinolorillajr** [comment]
Thanks for the update @robin-ho . Looks a lot better now.
Will review the partial translations so we can merge this pull request.
Please don't commit your other changes yet so we can close this.

**Comment by mind-blast** [comment]
understood. @severinolorillajr

**Comment by severinolorillajr** [comment]
Already reviewed your partial translations @robin-ho .
Please update accordingly based on my email.
Thanks.

**Comment by mind-blast** [comment]
Updated tagging.asc partial translation. Thank you.

**Pull request merged**
