### PR TITLE
Update policy.asc  Filipino Translation - 1131 Words

### PR DESCRIPTION
**Pull request by cordeta**
Partial Translation from Line 1 to 240 

Kindly check Thank You  :)

### CODE REVIEW

**Comment by severinolorillajr** [comment]
Hi @cordeta ,

Thank you for your interest in contributing to this project.
However, we have already assigned most of the chapters to our team and this conflicts with the ongoing work that we had. So I can't accept this PR, sorry.

If you are looking for other projects,
you can join us at discord: https://discord.gg/ZSxGRz

Thanks.

**Comment by cordeta** [comment]
It was my first try actually sir . My first ride with Github well. Thank you for the invitation. I joined the Discord channel :) Thanks ! 

Thank you for your response sir

**Comment by severinolorillajr** [comment]
@cordeta Well done..
Check our projects at discord, we have a recently opened project.
Just make sure to follow the guidelines.
Thanks.

**Comment by cordeta** [comment]
Yes sir ! :) This would be a fun-learning after all and at te same time be able to review Tagalog  :) 

I'll read all the faq's and guidelines first. Thank you sir

**Pull request closed without merging**
